export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS';
export const POST_REGISTRATION_FAILURE = 'POST_REGISTRATION_FAILURE';
export const POST_REGISTRATION_EXISTING_EMAIL =
  ' POST_REGISTRATION_EXISTING_EMAIL';
export const POST_REGISTRATION_CONFIRMATION = 'POST_REGISTRATION_CONFIRMATION';
