export const LOGIN_BLOG_SUCCESS = 'LOGIN_BLOG_SUCCESS';
export const LOGIN_BLOG_FAILURE = 'LOGIN_BLOG_FAILURE';
export const LOGIN_USER_AND_PWD_FAILURE_MESSAGE =
  'LOGIN_USER_AND_PWD_FAILURE_MESSAGE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
